packages:
  - web
  - packages/*

catalog:
  # Workflow & Build Tools (Root)
  "@commitlint/cli": "^20.2.0"
  "@commitlint/config-conventional": "^20.2.0"
  commitizen: "^4.3.1"
  cz-conventional-changelog: "^3.3.0"
  husky: "^9.1.7"
  turbo: "^2.7.2"

  # Core & Build Tools
  "@types/node": "^25.0.3"
  tsx: "^4.21.0"
  typescript: "^5.9.3"

  # React & UI
  "@tailwindcss/postcss": "^4"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  next: "16.1.1"
  react: "19.2.3"
  react-dom: "19.2.3"
  tailwindcss: "^4"

  # Backend, API & Data
  "@prisma/client": "^7.2.0"
  "@trpc/server": "^11.8.1"
  prisma: "^7.2.0"
  superjson: "^2.2.6"
  zod: "^4.2.1"

  # Linting & Config
  "@trivago/prettier-plugin-sort-imports": "6.0.0"
  eslint: "^9"
  eslint-config-next: "16.1.1"
  eslint-plugin-turbo: ^2.7.2
  prettier: "^3.7.4"
  prettier-plugin-tailwindcss: "0.7.2"

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
