packages:
  - web
  - packages/*

catalog:
  '@auth/prisma-adapter': ^2.11.1
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@hookform/resolvers': ^5.2.2
  '@prisma/client': ^6.19.1
  '@radix-ui/react-dialog': ^1.1.15
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-slot': ^1.2.4
  '@sentry/nextjs': ^10.32.1
  '@tailwindcss/postcss': ^4
  '@tanstack/react-query': ^5.90.16
  '@trivago/prettier-plugin-sort-imports': 6.0.0
  '@trpc/client': ^11.8.1
  '@trpc/react-query': ^11.8.1
  '@trpc/server': ^11.8.1
  '@types/node': ^25.0.3
  '@types/react': ^19
  '@types/react-dom': ^19
  class-variance-authority: ^0.7.1
  clsx: ^2.1.0
  cmdk: ^1.1.1
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  date-fns: ^4.1.0
  eslint: 9.39.2
  eslint-config-next: 16.1.1
  eslint-plugin-turbo: ^2.7.2
  globals: ^16.5.0
  husky: ^9.1.7
  lucide-react: 0.562.0
  next: 16.1.1
  next-auth: 4.24.13
  openai: ^6.15.0
  prettier: 3.7.4
  prettier-plugin-tailwindcss: 0.7.2
  prisma: ^6.19.1
  react: 19.2.3
  react-day-picker: ^9.13.0
  react-dom: 19.2.3
  react-hook-form: ^7.69.0
  superjson: ^2.2.6
  tailwind-merge: ^3.4.0
  tailwindcss: ^4
  tsx: ^4.21.0
  turbo: ^2.7.2
  typescript: ^5.9.3
  typescript-eslint: 8.51.0
  zod: 4.3.4

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
