packages:
  - "web"
  - "packages/*"

catalog:
  # Workflow & Build Tools (Root)
  "commitizen": "^4.3.1"
  "cz-conventional-changelog": "^3.3.0"
  "husky": "^9.1.7"
  "@commitlint/cli": "^20.2.0"
  "@commitlint/config-conventional": "^20.2.0"

  # Core & Build Tools
  "tsx": "^4.21.0"
  "typescript": "^5.9.3"
  "@types/node": "^25.0.3"

  # React & UI
  "next": "16.1.1"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "tailwindcss": "^4"
  "@tailwindcss/postcss": "^4"
  "@types/react": "^19"
  "@types/react-dom": "^19"

  # Backend, API & Data
  "prisma": "^7.2.0"
  "superjson": "^2.2.6"
  "zod": "^4.2.1"
  "@prisma/client": "^7.2.0"
  "@trpc/server": "^11.8.1"

  # Linting & Config
  "eslint": "^9"
  "eslint-config-next": "16.1.1"
