packages:
  - apps/*
  - packages/*

catalog:
  '@auth/prisma-adapter': ^2.11.1
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  '@hookform/resolvers': ^5.2.2
  '@logtail/node': '^0.5.6'
  '@playwright/test': ^1.57.0
  '@prisma/adapter-pg': '^7.4.0'
  '@prisma/client': ^7.4.0
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-popover': ^1.1.15
  '@radix-ui/react-progress': ^1.1.8
  '@radix-ui/react-scroll-area': ^1.2.10
  '@radix-ui/react-slot': 1.2.4
  '@radix-ui/react-tabs': ^1.1.13
  '@sentry/nextjs': 10.32.1
  '@t3-oss/env-nextjs': ^0.13.10
  '@tailwindcss/postcss': ^4
  '@tanstack/react-query': ^5.90.16
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  '@trivago/prettier-plugin-sort-imports': 6.0.0
  '@trpc/client': ^11.8.1
  '@trpc/react-query': ^11.8.1
  '@trpc/server': ^11.8.1
  '@types/pg': '^8.16.0'
  '@types/node': 25.0.3
  '@types/react': ^19
  '@types/react-dom': ^19
  '@vercel/analytics': ^1.6.1
  '@vercel/speed-insights': ^1.3.1
  '@vis.gl/react-google-maps': ^1.7.1
  '@vitejs/plugin-react': ^5.1.3
  '@vitest/coverage-v8': 4.0.17
  bullmq: '^5.69.1'
  class-variance-authority: ^0.7.1
  clsx: ^2.1.0
  cmdk: ^1.1.1
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
  date-fns: ^4.1.0
  dotenv: 17.2.3
  dotenv-cli: ^11.0.0
  eslint: 9.39.2
  eslint-config-next: 16.1.5
  eslint-plugin-turbo: ^2.7.2
  globals: ^16.5.0
  husky: ^9.1.7
  ioredis: 5.9.2
  jsdom: ^28.0.0
  lint-staged: ^16.2.7
  lucide-react: 0.562.0
  next: 16.1.5
  next-auth: 4.24.13
  openai: ^6.15.0
  pg: '^8.18.0'
  'posthog-js': '^1.351.1'
  prettier: 3.7.4
  prettier-plugin-tailwindcss: 0.7.2
  prisma: ^7.4.0
  react: 19.2.3
  react-day-picker: ^9.13.0
  react-dom: 19.2.3
  react-hook-form: ^7.69.0
  superjson: ^2.2.6
  tailwind-merge: ^3.4.0
  tailwindcss: ^4
  'tsup': '^8.5.1'
  tsx: 4.21.0
  turbo: ^2.7.2
  typescript: ^5.9.3
  typescript-eslint: 8.51.0
  vite-tsconfig-paths: ^6.1.0
  vitest: 4.0.17
  vitest-mock-extended: 3.1.0
  zod: 4.3.4

onlyBuiltDependencies:
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
