import { Suspense } from 'react';

import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter, JetBrains_Mono, Playfair_Display } from 'next/font/google';

import { AuthModal } from '@/components/auth-modal';
import Footer from '@/components/footer';
import { TRPCReactProvider } from '@/trpc/react';

import Header from '../components/header';
import './globals.css';
import { Providers } from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
  display: 'swap',
});

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${jetbrainsMono.variable} ${playfair.variable} flex min-h-screen flex-col antialiased`}
      >
        <Providers>
          <TRPCReactProvider>
            <Header />
            <div className="flex w-full flex-1 flex-col">{children}</div>
            <Suspense fallback={null}>
              <AuthModal />
            </Suspense>
            <Footer />
          </TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
