export const POPULAR_DESTINATIONS = [
  // --- EUROPE ---
  { value: 'paris', label: 'Paris, France' },
  { value: 'london', label: 'London, UK' },
  { value: 'rome', label: 'Rome, Italy' },
  { value: 'barcelona', label: 'Barcelona, Spain' },
  { value: 'amsterdam', label: 'Amsterdam, Netherlands' },
  { value: 'prague', label: 'Prague, Czech Republic' },
  { value: 'lisbon', label: 'Lisbon, Portugal' },
  { value: 'santorini', label: 'Santorini, Greece' },
  { value: 'venice', label: 'Venice, Italy' },
  { value: 'florence', label: 'Florence, Italy' },
  { value: 'athens', label: 'Athens, Greece' },
  { value: 'berlin', label: 'Berlin, Germany' },
  { value: 'vienna', label: 'Vienna, Austria' },
  { value: 'dublin', label: 'Dublin, Ireland' },
  { value: 'edinburgh', label: 'Edinburgh, Scotland' },
  { value: 'budapest', label: 'Budapest, Hungary' },
  { value: 'istanbul', label: 'Istanbul, Turkey' },
  { value: 'reykjavik', label: 'Reykjavik, Iceland' },
  { value: 'zurich', label: 'Zurich, Switzerland' },
  { value: 'copenhagen', label: 'Copenhagen, Denmark' },

  // --- ASIA ---
  { value: 'tokyo', label: 'Tokyo, Japan' },
  { value: 'kyoto', label: 'Kyoto, Japan' },
  { value: 'osaka', label: 'Osaka, Japan' },
  { value: 'bali', label: 'Bali, Indonesia' },
  { value: 'bangkok', label: 'Bangkok, Thailand' },
  { value: 'phuket', label: 'Phuket, Thailand' },
  { value: 'singapore', label: 'Singapore' },
  { value: 'seoul', label: 'Seoul, South Korea' },
  { value: 'dubai', label: 'Dubai, UAE' },
  { value: 'hanoi', label: 'Hanoi, Vietnam' },
  { value: 'ho-chi-minh', label: 'Ho Chi Minh City, Vietnam' },
  { value: 'hong-kong', label: 'Hong Kong' },
  { value: 'marrakech', label: 'Marrakech, Morocco' },
  { value: 'mumbai', label: 'Mumbai, India' },
  { value: 'delhi', label: 'New Delhi, India' },
  { value: 'jaipur', label: 'Jaipur, India' },
  { value: 'maldives', label: 'Maldives' },

  // --- NORTH AMERICA ---
  { value: 'new-york', label: 'New York, USA' },
  { value: 'los-angeles', label: 'Los Angeles, USA' },
  { value: 'san-francisco', label: 'San Francisco, USA' },
  { value: 'las-vegas', label: 'Las Vegas, USA' },
  { value: 'miami', label: 'Miami, USA' },
  { value: 'orlando', label: 'Orlando, USA' },
  { value: 'chicago', label: 'Chicago, USA' },
  { value: 'honolulu', label: 'Honolulu, Hawaii' },
  { value: 'vancouver', label: 'Vancouver, Canada' },
  { value: 'toronto', label: 'Toronto, Canada' },
  { value: 'montreal', label: 'Montreal, Canada' },
  { value: 'mexico-city', label: 'Mexico City, Mexico' },
  { value: 'cancun', label: 'Cancun, Mexico' },

  // --- SOUTH AMERICA ---
  { value: 'rio-de-janeiro', label: 'Rio de Janeiro, Brazil' },
  { value: 'buenos-aires', label: 'Buenos Aires, Argentina' },
  { value: 'cusco', label: 'Cusco, Peru' },
  { value: 'lima', label: 'Lima, Peru' },
  { value: 'cartagena', label: 'Cartagena, Colombia' },

  // --- OCEANIA & AFRICA ---
  { value: 'sydney', label: 'Sydney, Australia' },
  { value: 'melbourne', label: 'Melbourne, Australia' },
  { value: 'auckland', label: 'Auckland, New Zealand' },
  { value: 'queenstown', label: 'Queenstown, New Zealand' },
  { value: 'cape-town', label: 'Cape Town, South Africa' },
  { value: 'cairo', label: 'Cairo, Egypt' },
];
